# /home/mike/.config/tmuxinator/mgc.yml

name: mgc
root: ~/

windows:
  - dir: c
  - blog: 
      root: ~/Workspaces/blog/
      panes:
        - c
  - mail: neomutt
  - irc: weechat
  - sys: 
      panes:
        - htop
        - journalctl -f
  - dot:
      root: ~/Dotfiles
      panes: 
        - c
        - cd dotbase && c
  - p:
      root: ~/Workspaces
      panes: 
        - c
